### ISSUE TITLE
404 error

### ISSUE THREAD

**Issue by imanbrouwer** [coursera-dl/coursera-dl#673]
### Subject of the issue
Script seems to log in properly, but gets a 404 error right away
There are other issue reports also with a 404 error, but my guess was that this is different since the error occurs before it even attempts to download content, but seems to occur ( guessing here ) that it occurs when asking what the content is.

### Your environment
* Operating System (name/version): Centos 7
* Python version: Python 3.4.8
* coursera-dl version: 0.11.2

### Steps to reproduce
../../my-coursera/coursera-dl/coursera-dl --debug -u xxx deep-neural-network
Coursera password for xxx:
root[main] coursera_dl version 0.11.2
root[main] Downloading class: deep-neural-network (1 / 1)
root[download_class] Downloading new style (on demand) class deep-neural-network
root[login] Initiating login.
root[login] There were no .coursera.org cookies to be cleared.
root[prepare_auth_headers] Forging cookie header: csrftoken=RULpmQA3UxlqGyfBdQCN; csrf2_token_m3Seki7K=lXRyVMIfMgL74fVCUtPlgItd.
urllib3.connectionpool[_new_conn] Starting new HTTPS connection (1): api.coursera.org:443
urllib3.connectionpool[_make_request] https://api.coursera.org:443 "POST /api/login/v3 HTTP/1.1" 200 None
root[login] Logged in on coursera.org.
urllib3.connectionpool[_make_request] https://api.coursera.org:443 "GET /api/opencourse.v1/course/deep-neural-network?showLockedItems=true HTTP/1.1" 404 56
root[get_reply] Error 404 Client Error: Not Found for url: https://api.coursera.org/api/opencourse.v1/course/deep-neural-network?showLockedItems=true getting page https://api.coursera.org/api/opencourse.v1/course/deep-neural-network?showLockedItems=true
root[get_reply] The server replied: {"message":"","statusCode":404}
root[main] HTTPError 404 Client Error: Not Found for url: https://api.coursera.org/api/opencourse.v1/course/deep-neural-network?showLockedItems=true
root[main] HTTPError 404 Client Error: Not Found for url: https://api.coursera.org/api/opencourse.v1/course/deep-neural-network?showLockedItems=true
Traceback (most recent call last):
  File "/mnt/data/ibrouwer2/projects/deep_learning_coursera/my-coursera/coursera-dl/coursera/coursera_dl.py", line 238, in main
    error_occurred, completed = download_class(args, class_name)
  File "/mnt/data/ibrouwer2/projects/deep_learning_coursera/my-coursera/coursera-dl/coursera/coursera_dl.py", line 213, in download_class
    return download_on_demand_class(args, class_name)
  File "/mnt/data/ibrouwer2/projects/deep_learning_coursera/my-coursera/coursera-dl/coursera/coursera_dl.py", line 140, in download_on_demand_class
    args.download_notebooks
  File "/mnt/data/ibrouwer2/projects/deep_learning_coursera/my-coursera/coursera-dl/coursera/extractors.py", line 53, in get_modules
    page = self._get_on_demand_syllabus(class_name)
  File "/mnt/data/ibrouwer2/projects/deep_learning_coursera/my-coursera/coursera-dl/coursera/extractors.py", line 66, in _get_on_demand_syllabus
    page = get_page(self._session, url)
  File "/mnt/data/ibrouwer2/projects/deep_learning_coursera/my-coursera/coursera-dl/coursera/network.py", line 85, in get_page
    reply = get_reply(session, url, post=post, data=data, headers=headers)
  File "/mnt/data/ibrouwer2/projects/deep_learning_coursera/my-coursera/coursera-dl/coursera/network.py", line 47, in get_reply
    reply.raise_for_status()
  File "/mnt/data/ibrouwer2/projects/deep_learning_coursera/my-coursera/lib/python3.4/site-packages/requests/models.py", line 939, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.coursera.org/api/opencourse.v1/course/deep-neural-network?showLockedItems=true
### Expected behaviour
Download some stuff!

### Actual behaviour
Crash right away

**Comment by vtortola** [comment]
It does not work even with courses that were working before.

**Comment by mvandervoet** [comment]
Same for me: "It does not work even with courses that were working before."

**Comment by balta2ar** [comment]
Hi, everyone! Thank you for reporting the problem, we have acknowledged it, we've heard you!

It looks like some old API URIs have been shutdown so we need to move on to the newer ones. Right now it's not clear how much needs to be updated. As you understand, it's going to take some time: there is no official docs for the API so one needs to take a thorough look at the new API methods, put them into code, test it properly, so that we all can enjoy coursera-dl again. As always, if anyone comes up with the fixes, pull requests are welcome.

Thank you for understanding.

**Comment by rjdp** [comment]
checkout this script  https://gist.github.com/rjdp/79bd3f8dbf883e57fff5bce4f5bb66c3 , No login required,  I used it to download all courses from Google IT support specialization, the code downloads video files only as that is what I wanted for my use case.

**Comment by rjdp** [comment]
@imanbrouwer @vtortola @mvandervoet try the gist in my previous comment, it can download whole specialization as well as individual course without login(apparantly coursera doesnt require authentication for the APIs being used in the gist), check the gist, I  have written few comments to explain the usage, have fun tinkering. the script is good temporarily while coursera-dl is being fixed, I did not care about quizzes and subtitles so that part is not the script. :)

**Comment by avgasanov** [comment]
@rjdp Where did you get specialization id? i've tried scrip as is (run with python) and it downloaded only one video

**Comment by ankita-v** [comment]
@rjdp, I am unable to download the courses, getting the error:   
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by rjdp** [comment]
@ankita-v  I think you are trying to download a single course,in  that case just "is_specialization" variable in the script to False, and at line 29 of the script enter the course Id , slug  , name manually. if it still doesnt work just let me know the course name you are trying to download and I will substitute the values into the script and share with you :)

**Comment by ankita-v** [comment]
@rjdp, I am trying to download courses for the Data Science specialization courses from John Hopkins university.
Thank you :)

**Comment by avgasanov** [comment]
Script currently doesn't work for courses with ":" in name in windows. Because it is trying to create folder that contains ":" and windows doesn't permit to do this. I've replaced 
`course['name']`
with 
'course['name'].replace(":", " -")

**Comment by rjdp** [comment]
@ankita-v https://dpaste.de/1xaP  check this script I have substituted the values , use it as it is, i insereted try except to skip courses in the specialization that have not started yet which caused issues previously.  Thanks @avgasanov

**Comment by rjdp** [comment]
@ankita-v  I found out that in case of the data specialization course you want to get , I was not getting correct course id from an API I was relying on so I have updated my code and checked that it now downloading all available courses use this https://gist.github.com/rjdp/79bd3f8dbf883e57fff5bce4f5bb66c3 as it is.

**Comment by ankita-v** [comment]
Thank you so much @rjdp

**Comment by anshabhi** [comment]
Hello Can you tell me where are the files being downloaded in Ubuntu 18? I couldn't find them anywhere. Right now I am getting the screen with frequently updating bps values. Is this the right behaviour? 
![screenshot from 2018-06-21 17-37-37](https://user-images.githubusercontent.com/19303696/41718192-e72aed4a-7579-11e8-9b50-4daff822e648.png)

**Comment by rjdp** [comment]
@anshabhi In the directory wher you started the script, by the way are you using updated script ?  screenshot looks weird only when on video completes(progress status look like "[=========================]") next video starts downloading.

**Comment by anshabhi** [comment]
Yes, I did use the latest version of script. However, I used bpython3 to run it from inside the terminal only. I don't know if that made some difference.
I am installing docker on my system and I will soon post an update. Thanks!

**Comment by rjdp** [comment]
@anshabhi the docker image I used to download also uses python3 and it worked fine for me

**Comment by rjdp** [comment]
@anshabhi I get it now, you have been pressing "Enter" while download right? the bps is speed bytes per second, and yes that is correct behavior, please update video_quality in script if you wants smaller size videos.

**Comment by anshabhi** [comment]
I have not used  docker before, and I am unable to figure out how to "open python repl". Can you please help me with this?

**Comment by anshabhi** [comment]
Thanks! Works like a charm !!

**Comment by yogeshbatra** [comment]
@rjdp what is the course id of google it course?

**Comment by rjdp** [comment]
`one_of_specialization_course_id =  "X2bX61doEeerkQ5vdwUqtA"`

**Comment by yogeshbatra** [comment]
@rjdp thanks

**Comment by Puppey** [comment]
Same for me.But it worked before.

**Comment by fredharvey** [comment]
the script @rjdp works well for courses and some specializations but not all specializations.

For example, it DOES NOT work for https://www.coursera.org/specializations/team-building or https://www.coursera.org/specializations/strategic-leadership

but does work for the data science included in the script.

If you look at the design/format of the specializations, the data science specialization is setup differently and does work.

**Comment by rjdp** [comment]
@fredharvey it will skip the courses in specialization that are yet to release, anyway let me look if there is something else wrong with the script that I have thought of. I myself have downloaded 4 specialization courses using same script.

**Comment by rjdp** [comment]
@fredharvey  probably you were trying with wrong course ids :

- for first specialization substitute `one_of_specialization_course_id =  "2vaX6li0Eeaw3QoEHqdPHw"`
- for second one substitute `one_of_specialization_course_id = "XupniISSEeWcSw7mZ7gPOw"`

**Comment by Zhijun166** [comment]
coursera_dl version 0.10.0
Downloading class: money-banking (1 / 1)
Logged in on coursera.org.
Error 404 Client Error: Not Found for url: https://www.coursera.org/api/opencourse.v1/course/money-banking?showLockedItems=true getting page https://www.coursera.org/api/opencourse.v1/course/money-banking?showLockedItems=true
The server replied: {"message":"","statusCode":404}
HTTPError 404 Client Error: Not Found for url: https://www.coursera.org/api/opencourse.v1/course/money-banking?showLockedItems=true

**Comment by Zhijun166** [comment]
Hello, I'm the version of windows7 and windows10, and I don't know the basics of programming. How should I make my coursera-dl back to normal? I'm experiencing the problem of 404, not found url. What should I do? , The easiest and most convenient recovery download function, thank you

**Comment by rjdp** [comment]
@Zhijun166 make sure `requests` package is installed (pip install requests) and download the script here https://pastebin.com/raw/BHm4qscG , save as `script.py` and run `python script.py` that will do the job.

**Comment by yogeshbatra** [comment]
@balta2ar some problem with downloading or resume course 
Version: 0.11.3 
Os: Windows 7 x64
i tried to download this course - https://www.coursera.org/learn/machine-learning(Not specialization)
i am already enrolled in this course and half of course is already completed but when i try to resume this course **coursera-dl** started download this course - https://www.coursera.org/specializations/machine-learning(specialization)
also tried to fresh download this course not working instead download another machine-learning(specializations) course

**Comment by balta2ar** [comment]
@yogeshbatra That's a bummer. Didn'd know they had specialization and regular courses with the same name. Fixed in 0.11.4. And added a flag `--specialization` to download specialization.

**Comment by alwayssummer** [comment]
Dumb question: How do I get the new version? If I run pip install I get 0.11.2.

**Comment by balta2ar** [comment]
```
pip install --upgrade coursera-dl
```
or
```
pip install --user --upgrade coursera-dl
```

**Comment by alwayssummer** [comment]
Just downloaded my course. Thanks!

**Comment by RahulGandhiOracle** [comment]
I'm still getting 404 error with latest coursera-dl version 0.11.4 on Windows 7

`coursera_dl version 0.11.4
Traceback (most recent call last):
  File "C:\coursera-dl-master\coursera\cookies.py", line 148, in login
    r.raise_for_status()
  File "C:\ProgramData\Anaconda3\lib\site-packages\requests\models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.coursera.org/api/login/v3

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\coursera-dl-master\\coursera-dl", line 6, in <module>
    coursera_dl.main()
  File "C:\coursera-dl-master\coursera\coursera_dl.py", line 236, in main
    login(session, args.username, args.password)
  File "C:\coursera-dl-master\coursera\cookies.py", line 155, in login
    raise AuthenticationFailed('Cannot login on coursera.org: %s' % e)
coursera.cookies.AuthenticationFailed: Cannot login on coursera.org: 400 Client Error: Bad Request for url: https://api.coursera.org/api/login/v3`

**Comment by ImSiddh** [comment]
I am getting error while resuming 
C:\coursera-dl-master>coursera-dl -u siddh.315@gmail.com --resume experimetation
Coursera password for siddh.315@gmail.com:
coursera_dl version 0.11.4
Traceback (most recent call last):
  File "C:\coursera-dl-master\coursera\cookies.py", line 148, in login
    r.raise_for_status()
  File "C:\Users\Siddharth\AppData\Roaming\Python\Python37\site-packages\requests\models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.coursera.org/api/login/v3

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\coursera-dl-master\\coursera-dl", line 6, in <module>
    coursera_dl.main()
  File "C:\coursera-dl-master\coursera\coursera_dl.py", line 236, in main
    login(session, args.username, args.password)
  File "C:\coursera-dl-master\coursera\cookies.py", line 155, in login
    raise AuthenticationFailed('Cannot login on coursera.org: %s' % e)
coursera.cookies.AuthenticationFailed: Cannot login on coursera.org: 400 Client Error: Bad Request for url: https://api.coursera.org/api/login/v3
