### ISSUE TITLE
[SOLVED] Coursera-dl stopped working completely with Error 403 Client Error due to upstream changes!

### ISSUE THREAD

**Issue by zenny** [coursera-dl/coursera-dl#800]
### Solution to the issue
https://github.com/coursera-dl/coursera-dl/issues/800#issuecomment-870953541

### Subject of the issue
For the last three days, the coursera-dl fails to download with the following error. Seems like a new bug.

```
Parsing syllabus of on-demand course (id=VotHm2ejEeqV5Aor8ms6Fw). This may take some time, please be patient ...
Error 403 Client Error: Forbidden for url: https://api.coursera.org/api/memberships.v1?includes=courseId,courses.v1&q=me&showHidden=true&filter=current,preEnrolled getting page https://api.coursera.org/api/memberships.v1?includes=courseId,courses.v1&q=me&showHidden=true&filter=current,preEnrolled
The server replied: {"errorCode":"Not Authorized","message":null,"details":null}
HTTPError 403 Client Error: Forbidden for url: https://api.coursera.org/api/memberships.v1?includes=courseId,courses.v1&q=me&showHidden=true&filter=current,preEnrolled
Sleeping for 60 seconds before downloading next course. You can change this with --download-delay option.
^CTraceback (most recent call last):
  File "/home/zenny/Downloads/Education/coursera/my-coursera/coursera-latest/./coursera-dl", line 6, in <module>
    coursera_dl.main()
  File "/home/zenny/Downloads/Education/coursera/my-coursera/coursera-latest/coursera/coursera_dl.py", line 271, in main
    time.sleep(args.download_delay)
KeyboardInterrupt
```

### Your environment
* Operating System (name/version): VoidLinux (Kernel v.  5.4.121)
* Python version: 3.9.5
* coursera-dl version:  0.11.5 (tried with both self-compiled and using pip without success!)

### Steps to reproduce
Tell us how to reproduce this issue, please don't forget to include
enough information so that you can help us help you:

* Is the problem happening with the latest version of the script?
Yes

* Do you have all the recommended versions of the modules? See them in the
  file `requirements.txt`.

Yes

* What is the course that you are trying to access?

`./coursera-dl --resume --clear-cache --aria2 --path=../courses  value-based-care-introduction pop-health managing-processes reimburse-models value-based-care-organizational-competencies value-based-care-quality-improvement-in-organizations`

Also tried with: `research-inquiry-discovery` as well as `guide-to-healthcare-innovation-principles-and-practice ghi-healthcare-entrepreneurship-taking-ideas-to-market ghi-healthcare-innovation-what-success-look-like-how-to-achieve`

* What is the precise command line that you are using (don't forget to obfuscate
  your username and password, but leave all other information untouched).

`./coursera-dl --resume --clear-cache --aria2 --path=../courses <CourseName>` with the following credentials in `coursera-dl.conf`

```
--username user@email.com
--password PaSSw0rd
--subtitle-language en
--video-resolution 720p
--download-quizzes True
--download-notebooks True
--cauth <COPIED FROM CAUTH SECTION OF THE COOKIES>
```

* What are the precise messages that you get? Please, use the `--debug`
  option before posting the messages as a bug report. Please, copy and paste
  them.  Don't reword/paraphrase the messages.

```
(my-coursera) [ zenny@MACHINE970AD3 ~/Downloads/Education/coursera/my-coursera/coursera-latest ]$ ./coursera-dl --resume --clear-cache --aria2 --path=../courses research-inquiry-discovery --debug
root[main] coursera_dl version 0.11.5
root[main] Downloading class: research-inquiry-discovery (1 / 1)
root[download_class] Downloading new style (on demand) class research-inquiry-discovery
urllib3.connectionpool[_new_conn] Starting new HTTPS connection (1): api.coursera.org:443
urllib3.connectionpool[_make_request] https://api.coursera.org:443 "GET /api/onDemandCourseMaterials.v2/?q=slug&slug=research-inquiry-discovery&includes=modules%2Clessons%2CpassableItemGroups%2CpassableItemGroupChoices%2CpassableLessonElements%2Citems%2Ctracks%2CgradePolicy&&fields=moduleIds%2ConDemandCourseMaterialModules.v1(name%2Cslug%2Cdescription%2CtimeCommitment%2ClessonIds%2Coptional%2ClearningObjectives)%2ConDemandCourseMaterialLessons.v1(name%2Cslug%2CtimeCommitment%2CelementIds%2Coptional%2CtrackId)%2ConDemandCourseMaterialPassableItemGroups.v1(requiredPassedCount%2CpassableItemGroupChoiceIds%2CtrackId)%2ConDemandCourseMaterialPassableItemGroupChoices.v1(name%2Cdescription%2CitemIds)%2ConDemandCourseMaterialPassableLessonElements.v1(gradingWeight%2CisRequiredForPassing)%2ConDemandCourseMaterialItems.v2(name%2Cslug%2CtimeCommitment%2CcontentSummary%2CisLocked%2ClockableByItem%2CitemLockedReasonCode%2CtrackId%2ClockedStatus%2CitemLockSummary)%2ConDemandCourseMaterialTracks.v1(passablesCount)&showLockedItems=true HTTP/1.1" 200 None
chardet.charsetprober[feed] EUC-JP Japanese prober hit error at byte 23215
chardet.charsetprober[feed] EUC-KR Korean prober hit error at byte 23215
chardet.charsetprober[feed] EUC-TW Taiwan prober hit error at byte 23215
chardet.charsetprober[get_confidence] utf-8  confidence = 0.938125
chardet.charsetprober[get_confidence] SHIFT_JIS Japanese confidence = 0.01
chardet.charsetprober[get_confidence] EUC-JP not active
chardet.charsetprober[get_confidence] GB2312 Chinese confidence = 0.01
chardet.charsetprober[get_confidence] EUC-KR not active
chardet.charsetprober[get_confidence] CP949 Korean confidence = 0.01
chardet.charsetprober[get_confidence] Big5 Chinese confidence = 0.01
chardet.charsetprober[get_confidence] EUC-TW not active
chardet.charsetprober[get_confidence] windows-1251 Russian confidence = 0.01
chardet.charsetprober[get_confidence] KOI8-R Russian confidence = 0.01
chardet.charsetprober[get_confidence] ISO-8859-5 Russian confidence = 0.01
chardet.charsetprober[get_confidence] MacCyrillic Russian confidence = 0.01
chardet.charsetprober[get_confidence] IBM866 Russian confidence = 0.01
chardet.charsetprober[get_confidence] IBM855 Russian confidence = 0.01
chardet.charsetprober[get_confidence] ISO-8859-7 Greek confidence = 0.0
chardet.charsetprober[get_confidence] windows-1253 Greek confidence = 0.0
chardet.charsetprober[get_confidence] ISO-8859-5 Bulgairan confidence = 0.01
chardet.charsetprober[get_confidence] windows-1251 Bulgarian confidence = 0.01
chardet.charsetprober[get_confidence] TIS-620 Thai confidence = 0.01
chardet.charsetprober[get_confidence] ISO-8859-9 Turkish confidence = 0.45077422345253365
chardet.charsetprober[get_confidence] windows-1255 Hebrew confidence = 0.0
chardet.charsetprober[get_confidence] windows-1255 Hebrew confidence = 0.0
chardet.charsetprober[get_confidence] windows-1255 Hebrew confidence = 0.0
chardet.charsetprober[get_confidence] utf-8  confidence = 0.938125
chardet.charsetprober[get_confidence] SHIFT_JIS Japanese confidence = 0.01
chardet.charsetprober[get_confidence] EUC-JP not active
chardet.charsetprober[get_confidence] GB2312 Chinese confidence = 0.01
chardet.charsetprober[get_confidence] EUC-KR not active
chardet.charsetprober[get_confidence] CP949 Korean confidence = 0.01
chardet.charsetprober[get_confidence] Big5 Chinese confidence = 0.01
chardet.charsetprober[get_confidence] EUC-TW not active
root[_get_on_demand_syllabus] Downloaded https://api.coursera.org/api/onDemandCourseMaterials.v2/?q=slug&slug=research-inquiry-discovery&includes=modules%2Clessons%2CpassableItemGroups%2CpassableItemGroupChoices%2CpassableLessonElements%2Citems%2Ctracks%2CgradePolicy&&fields=moduleIds%2ConDemandCourseMaterialModules.v1(name%2Cslug%2Cdescription%2CtimeCommitment%2ClessonIds%2Coptional%2ClearningObjectives)%2ConDemandCourseMaterialLessons.v1(name%2Cslug%2CtimeCommitment%2CelementIds%2Coptional%2CtrackId)%2ConDemandCourseMaterialPassableItemGroups.v1(requiredPassedCount%2CpassableItemGroupChoiceIds%2CtrackId)%2ConDemandCourseMaterialPassableItemGroupChoices.v1(name%2Cdescription%2CitemIds)%2ConDemandCourseMaterialPassableLessonElements.v1(gradingWeight%2CisRequiredForPassing)%2ConDemandCourseMaterialItems.v2(name%2Cslug%2CtimeCommitment%2CcontentSummary%2CisLocked%2ClockableByItem%2CitemLockedReasonCode%2CtrackId%2ClockedStatus%2CitemLockSummary)%2ConDemandCourseMaterialTracks.v1(passablesCount)&showLockedItems=true (25014 bytes)
root[_parse_on_demand_syllabus] Parsing syllabus of on-demand course (id=IAGMLXkjEequHgrfnjtqcQ). This may take some time, please be patient ...
urllib3.connectionpool[_make_request] https://api.coursera.org:443 "GET /api/memberships.v1?includes=courseId,courses.v1&q=me&showHidden=true&filter=current,preEnrolled HTTP/1.1" 403 None
root[get_reply] Error 403 Client Error: Forbidden for url: https://api.coursera.org/api/memberships.v1?includes=courseId,courses.v1&q=me&showHidden=true&filter=current,preEnrolled getting page https://api.coursera.org/api/memberships.v1?includes=courseId,courses.v1&q=me&showHidden=true&filter=current,preEnrolled
root[get_reply] The server replied: {"errorCode":"Not Authorized","message":null,"details":null}
root[main] HTTPError 403 Client Error: Forbidden for url: https://api.coursera.org/api/memberships.v1?includes=courseId,courses.v1&q=me&showHidden=true&filter=current,preEnrolled
root[main] HTTPError 403 Client Error: Forbidden for url: https://api.coursera.org/api/memberships.v1?includes=courseId,courses.v1&q=me&showHidden=true&filter=current,preEnrolled
Traceback (most recent call last):
  File "/home/zenny/Downloads/Education/coursera/my-coursera/coursera-latest/coursera/coursera_dl.py", line 247, in main
    error_occurred, completed = download_class(
  File "/home/zenny/Downloads/Education/coursera/my-coursera/coursera-latest/coursera/coursera_dl.py", line 214, in download_class
    return download_on_demand_class(session, args, class_name)
  File "/home/zenny/Downloads/Education/coursera/my-coursera/coursera-latest/coursera/coursera_dl.py", line 134, in download_on_demand_class
    error_occurred, modules = extractor.get_modules(
  File "/home/zenny/Downloads/Education/coursera/my-coursera/coursera-latest/coursera/extractors.py", line 53, in get_modules
    error_occurred, modules = self._parse_on_demand_syllabus(
  File "/home/zenny/Downloads/Education/coursera/my-coursera/coursera-latest/coursera/extractors.py", line 104, in _parse_on_demand_syllabus
    course.obtain_user_id()
  File "/home/zenny/Downloads/Education/coursera/my-coursera/coursera-latest/coursera/api.py", line 623, in obtain_user_id
    reply = get_page(self._session, OPENCOURSE_MEMBERSHIPS, json=True)
  File "/home/zenny/Downloads/Education/coursera/my-coursera/coursera-latest/coursera/network.py", line 91, in get_page
    reply = get_reply(session, url, post=post, data=data, headers=headers,
  File "/home/zenny/Downloads/Education/coursera/my-coursera/coursera-latest/coursera/network.py", line 51, in get_reply
    reply.raise_for_status()
  File "/home/zenny/Downloads/Education/coursera/my-coursera/lib/python3.9/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://ai.coursera.org/api/memberships.v1?includes=courseId,courses.v1&q=me&showHidden=true&filter=current,preEnrolled
```

### Expected behaviour
The command should download the course.

### Actual behaviour

Fails to download with 403 error even with correct login, password and cauth

```
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://ai.coursera.org/api/memberships.v1?includes=courseId,courses.v1&q=me&showHidden=true&filter=current,preEnrolled
```

**Comment by zenny** [comment]
UPDATE: Even trying to list enrolled courses gave 400  error:

```
$ ./coursera-dl --list-courses --debug
root[main] coursera_dl version 0.11.5
root[main] Listing enrolled courses
root[login] Initiating login.
root[login] There were no .coursera.org cookies to be cleared.
root[prepare_auth_headers] Forging cookie header: csrftoken=8ldvhChH9qQPtknYpdxh; csrf2_token_GII5QY7r=6PGdw5R3SSLuhbr3PlB4RDBn.
urllib3.connectionpool[_new_conn] Starting new HTTPS connection (1): api.coursera.org:443
urllib3.connectionpool[_make_request] https://api.coursera.org:443 "POST /api/login/v3 HTTP/1.1" 400 None
Traceback (most recent call last):
  File "/xtbmr/HOMEPOOL/HOME/VOIDHOME.BAK/zenny/Downloads/Education/coursera/my-coursera/coursera-dl/coursera/cookies.py", line 148, in login
    r.raise_for_status()
  File "/xtbmr/HOMEPOOL/HOME/VOIDHOME.BAK/zenny/Downloads/Education/coursera/my-coursera/lib/python3.9/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.coursera.org/api/login/v3

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/xtbmr/HOMEPOOL/HOME/VOIDHOME.BAK/zenny/Downloads/Education/coursera/my-coursera/coursera-dl/./coursera-dl", line 6, in <module>
    coursera_dl.main()
  File "/xtbmr/HOMEPOOL/HOME/VOIDHOME.BAK/zenny/Downloads/Education/coursera/my-coursera/coursera-dl/coursera/coursera_dl.py", line 232, in main
    list_courses(args)
  File "/xtbmr/HOMEPOOL/HOME/VOIDHOME.BAK/zenny/Downloads/Education/coursera/my-coursera/coursera-dl/coursera/coursera_dl.py", line 108, in list_courses
    login(session, args.username, args.password)
  File "/xtbmr/HOMEPOOL/HOME/VOIDHOME.BAK/zenny/Downloads/Education/coursera/my-coursera/coursera-dl/coursera/cookies.py", line 155, in login
    raise AuthenticationFailed('Cannot login on coursera.org: %s' % e)
coursera.cookies.AuthenticationFailed: Cannot login on coursera.org: 400 Client Error: Bad Request for url: https://api.coursera.org/api/login/v3
```

It appears there was a major overhaul upstream (@coursera) as there are similar recent reports described briefly in  #796 and #799, imho.

**Comment by dakdouky** [comment]
I think this might have to do with the new reCAPTCHA recently (very late last month) used by Coursera to log in. So, I guess authentication fails as the login process is not able to bypass this reCAPTCHA.

Hope this gets resolved soon.

**Comment by zenny** [comment]
> I think this might have to do with the new reCAPTCHA recently (very late last month) used by Coursera to log in. So, I guess authentication fails as the login process is not able to bypass this reCAPTCHA.
> 
> Hope this gets resolved soon.

Methink, too.

**Comment by zenny** [comment]
Bump! Any pointer to overcome this situation shall be appreciated!

**Comment by quantumgolem** [comment]
Having the same issue here. As a matter of fact, when I try to run the command in the terminal it logs me out of the browser, meaning I need to log in again and create a new CAUTH token

**Comment by locknet11** [comment]
Same issue in Ubuntu Desktop 20.04 using CAUTH token.

**Comment by t-AIR-e** [comment]
> 
> 
> Having the same issue here. As a matter of fact, when I try to run the command in the terminal it logs me out of the browser, meaning I need to log in again and create a new CAUTH token

Yup I'm same thing for me

**Comment by dobomode** [comment]
Since `coursera-dl` is currently not working and as one of my course subscriptions expires tomorrow, I decided to build a small project and implemented a lightweight Node.js script to download the assets & videos for a given Coursera course.

I hope this provides a working solution for people, while we are waiting for a fix here.

You can access the project here:
[coursera-scraper](https://github.com/dobomode/coursera-scraper)

**Comment by zenny** [comment]
> Since `coursera-dl` is currently not working and as one of my course subscriptions expires tomorrow, I decided to build a small project and implemented a lightweight Node.js script to download the assets & videos for a given Coursera course.
> 
> I hope this provides a working solution for people, while we are waiting for a fix here.
> 
> You can access the project here:
> [coursera-scraper](https://github.com/dobomode/coursera-scraper)

@dobomode Thanks.

It would be nice if you add the feature to download `reading lectures` and `pdf` at least, if not `jupyter-notebooks`. (some proposals are also posted in https://github.com/dobomode/coursera-scraper/issues/2)

**Comment by MatiasAgelvis** [comment]
This issue is fixed in https://github.com/coursera-dl/coursera-dl/pull/798, while this fork is merged we can download NightMachinary's fork directly.

**Comment by zenny** [comment]
> This issue is fixed in #798, while this fork is merged we can download NightMachinary's fork directly.

@MatiasAgelvis, Thanks for the pointer, but  didn't work even after pulling @NightMachinary's fork ( https://github.com/NightMachinary/coursera-dl) at my end:

```
$ ./coursera-dl --resume --path=../courses research-inquiry-discovery
/home/zenny/Downloads/Education/coursera/my-coursera/NightMachinary-coursera-dl/coursera/api.py:948: SyntaxWarning: "is" with a literal. Did you
mean "=="?
  if extension is '':
/home/zenny/Downloads/Education/coursera/my-coursera/NightMachinary-coursera-dl/coursera/api.py:1593: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if extension is '':
coursera_dl version 0.11.5
Downloading class: research-inquiry-discovery (1 / 1)
Parsing syllabus of on-demand course (id=IAGMLXkjEequHgrfnjtqcQ). This may take some time, please be patient ...
Error 403 Client Error: Forbidden for url: https://api.coursera.org/api/memberships.v1?incudes=courseId,courses.v1&q=me&showHidden=true&filter=current,preEnrolled getting page https://api.coursera.org/api/memberships.v1?includes=courseId,courses.v1&q=me&showHidden=true&filter=current,preEnrolled
The server replied: {"errorCode":"Not Authorized","message":null,"details":null}
```

**Comment by zenny** [comment]
> > This issue is fixed in #798, while this fork is merged we can download NightMachinary's fork directly.
> 
> @MatiasAgelvis, Thanks for the pointer, but didn't work even after pulling @NightMachinary's fork ( https://github.com/NightMachinary/coursera-dl) at my end:
> 
> ```
> $ ./coursera-dl --resume --path=../courses research-inquiry-discovery
> /home/zenny/Downloads/Education/coursera/my-coursera/NightMachinary-coursera-dl/coursera/api.py:948: SyntaxWarning: "is" with a literal. Did you
> mean "=="?
>   if extension is '':
> /home/zenny/Downloads/Education/coursera/my-coursera/NightMachinary-coursera-dl/coursera/api.py:1593: SyntaxWarning: "is" with a literal. Did you mean "=="?
>   if extension is '':
> coursera_dl version 0.11.5
> Downloading class: research-inquiry-discovery (1 / 1)
> Parsing syllabus of on-demand course (id=IAGMLXkjEequHgrfnjtqcQ). This may take some time, please be patient ...
> Error 403 Client Error: Forbidden for url: https://api.coursera.org/api/memberships.v1?incudes=courseId,courses.v1&q=me&showHidden=true&filter=current,preEnrolled getting page https://api.coursera.org/api/memberships.v1?includes=courseId,courses.v1&q=me&showHidden=true&filter=current,preEnrolled
> The server replied: {"errorCode":"Not Authorized","message":null,"details":null}
> ```

This was solved by applying a patch (https://github.com/coursera-dl/edx-dl/commit/5490a99a98b56f544661c131229ef640ace2b064) to `utils.py` as mentioned in https://github.com/coursera-dl/coursera-dl/issues/778#issuecomment-719658361

**Comment by zenny** [comment]
> > > This issue is fixed in #798, while this fork is merged we can download NightMachinary's fork directly.
> > 
> > 
> > @MatiasAgelvis, Thanks for the pointer, but didn't work even after pulling @NightMachinary's fork ( https://github.com/NightMachinary/coursera-dl) at my end:
> > ```
> > $ ./coursera-dl --resume --path=../courses research-inquiry-discovery
> > /home/zenny/Downloads/Education/coursera/my-coursera/NightMachinary-coursera-dl/coursera/api.py:948: SyntaxWarning: "is" with a literal. Did you
> > mean "=="?
> >   if extension is '':
> > /home/zenny/Downloads/Education/coursera/my-coursera/NightMachinary-coursera-dl/coursera/api.py:1593: SyntaxWarning: "is" with a literal. Did you mean "=="?
> >   if extension is '':
> > coursera_dl version 0.11.5
> > Downloading class: research-inquiry-discovery (1 / 1)
> > Parsing syllabus of on-demand course (id=IAGMLXkjEequHgrfnjtqcQ). This may take some time, please be patient ...
> > Error 403 Client Error: Forbidden for url: https://api.coursera.org/api/memberships.v1?incudes=courseId,courses.v1&q=me&showHidden=true&filter=current,preEnrolled getting page https://api.coursera.org/api/memberships.v1?includes=courseId,courses.v1&q=me&showHidden=true&filter=current,preEnrolled
> > The server replied: {"errorCode":"Not Authorized","message":null,"details":null}
> > ```
> 
> This was solved by applying a patch ([coursera-dl/edx-dl@5490a99](https://github.com/coursera-dl/edx-dl/commit/5490a99a98b56f544661c131229ef640ace2b064)) to `utils.py` as mentioned in [#778 (comment)](https://github.com/coursera-dl/coursera-dl/issues/778#issuecomment-719658361)

The issue is not yet solved while downloading courses in batch:

```
Error 403 Client Error: Forbidden for url: https://api.coursera.org/api/onDemandCourseMaterials.v2/?q=slug&slug=scholoarly-communication&includes=modules%2Clessons%2CpassableItemGroups%2CpassableItemGroupChoices%2CpassableLessonElements%2Citems%2Ctracks%2CgradePolicy&&fields=moduleIds%2ConDemandCourseMaterialModules.v1(name%2Cslug%2Cdescription%2CtimeCommitment%2ClessonIds%2Coptional%2ClearningObjectives)%2ConDemandCourseMaterialLessons.v1(name%2Cslug%2CtimeCommitment%2CelementIds%2Coptional%2CtrackId)%2ConDemandCourseMaterialPassableItemGroups.v1(requiredPassedCount%2CpassableItemGroupChoiceIds%2CtrackId)%2ConDemandCourseMaterialPassableItemGroupChoices.v1(name%2Cdescription%2CitemIds)%2ConDemandCourseMaterialPassableLessonElements.v1(gradingWeight%2CisRequiredForPassing)%2ConDemandCourseMaterialItems.v2(name%2Cslug%2CtimeCommitment%2CcontentSummary%2CisLocked%2ClockableByItem%2CitemLockedReasonCode%2CtrackId%2ClockedStatus%2CitemLockSummary)%2ConDemandCourseMaterialTracks.v1(passablesCount)&showLockedItems=true getting page https://api.coursera.org/api/onDemandCourseMaterials.v2/?q=slug&slug=scholoarly-communication&includes=modules%2Clessons%2CpassableItemGroups%2CpassableItemGroupChoices%2CpassableLessonElements%2Citems%2Ctracks%2CgradePolicy&&fields=moduleIds%2ConDemandCourseMaterialModules.v1(name%2Cslug%2Cdescription%2CtimeCommitment%2ClessonIds%2Coptional%2ClearningObjectives)%2ConDemandCourseMaterialLessons.v1(name%2Cslug%2CtimeCommitment%2CelementIds%2Coptional%2CtrackId)%2ConDemandCourseMaterialPassableItemGroups.v1(requiredPassedCount%2CpassableItemGroupChoiceIds%2CtrackId)%2ConDemandCourseMaterialPassableItemGroupChoices.v1(name%2Cdescription%2CitemIds)%2ConDemandCourseMaterialPassableLessonElements.v1(gradingWeight%2CisRequiredForPassing)%2ConDemandCourseMaterialItems.v2(name%2Cslug%2CtimeCommitment%2CcontentSummary%2CisLocked%2ClockableByItem%2CitemLockedReasonCode%2CtrackId%2ClockedStatus%2CitemLockSummary)%2ConDemandCourseMaterialTracks.v1(passablesCount)&showLockedItems=true
The server replied: {"errorCode":"Not Authorized","message":null,"details":null}
HTTPError 403 Client Error: Forbidden for url: https://api.coursera.org/api/onDemandCourseMaterials.v2/?q=slug&slug=scholoarly-communication&includes=modules%2Clessons%2CpassableItemGroups%2CpassableItemGroupChoices%2CpassableLessonElements%2Citems%2Ctracks%2CgradePolicy&&fields=moduleIds%2ConDemandCourseMaterialModules.v1(name%2Cslug%2Cdescription%2CtimeCommitment%2ClessonIds%2Coptional%2ClearningObjectives)%2ConDemandCourseMaterialLessons.v1(name%2Cslug%2CtimeCommitment%2CelementIds%2Coptional%2CtrackId)%2ConDemandCourseMaterialPassableItemGroups.v1(requiredPassedCount%2CpassableItemGroupChoiceIds%2CtrackId)%2ConDemandCourseMaterialPassableItemGroupChoices.v1(name%2Cdescription%2CitemIds)%2ConDemandCourseMaterialPassableLessonElements.v1(gradingWeight%2CisRequiredForPassing)%2ConDemandCourseMaterialItems.v2(name%2Cslug%2CtimeCommitment%2CcontentSummary%2CisLocked%2ClockableByItem%2CitemLockedReasonCode%2CtrackId%2ClockedStatus%2CitemLockSummary)%2ConDemandCourseMaterialTracks.v1(passablesCount)&showLockedItems=true
Sleeping for 60 seconds before downloading next course. You can change this with --download-delay option.
```

**Comment by zenny** [comment]
> > > > This issue is fixed in #798, while this fork is merged we can download NightMachinary's fork directly.
> > > 
> > > 
> > > @MatiasAgelvis, Thanks for the pointer, but didn't work even after pulling @NightMachinary's fork ( https://github.com/NightMachinary/coursera-dl) at my end:
> > > ```
> > > $ ./coursera-dl --resume --path=../courses research-inquiry-discovery
> > > /home/zenny/Downloads/Education/coursera/my-coursera/NightMachinary-coursera-dl/coursera/api.py:948: SyntaxWarning: "is" with a literal. Did you
> > > mean "=="?
> > >   if extension is '':
> > > /home/zenny/Downloads/Education/coursera/my-coursera/NightMachinary-coursera-dl/coursera/api.py:1593: SyntaxWarning: "is" with a literal. Did you mean "=="?
> > >   if extension is '':
> > > coursera_dl version 0.11.5
> > > Downloading class: research-inquiry-discovery (1 / 1)
> > > Parsing syllabus of on-demand course (id=IAGMLXkjEequHgrfnjtqcQ). This may take some time, please be patient ...
> > > Error 403 Client Error: Forbidden for url: https://api.coursera.org/api/memberships.v1?incudes=courseId,courses.v1&q=me&showHidden=true&filter=current,preEnrolled getting page https://api.coursera.org/api/memberships.v1?includes=courseId,courses.v1&q=me&showHidden=true&filter=current,preEnrolled
> > > The server replied: {"errorCode":"Not Authorized","message":null,"details":null}
> > > ```
> > 
> > 
> > This was solved by applying a patch ([coursera-dl/edx-dl@5490a99](https://github.com/coursera-dl/edx-dl/commit/5490a99a98b56f544661c131229ef640ace2b064)) to `utils.py` as mentioned in [#778 (comment)](https://github.com/coursera-dl/coursera-dl/issues/778#issuecomment-719658361)
> 
> The issue is not yet solved while downloading courses in batch:
> 
> ```
> Error 403 Client Error: Forbidden for url: https://api.coursera.org/api/onDemandCourseMaterials.v2/?q=slug&slug=scholoarly-communication&includes=modules%2Clessons%2CpassableItemGroups%2CpassableItemGroupChoices%2CpassableLessonElements%2Citems%2Ctracks%2CgradePolicy&&fields=moduleIds%2ConDemandCourseMaterialModules.v1(name%2Cslug%2Cdescription%2CtimeCommitment%2ClessonIds%2Coptional%2ClearningObjectives)%2ConDemandCourseMaterialLessons.v1(name%2Cslug%2CtimeCommitment%2CelementIds%2Coptional%2CtrackId)%2ConDemandCourseMaterialPassableItemGroups.v1(requiredPassedCount%2CpassableItemGroupChoiceIds%2CtrackId)%2ConDemandCourseMaterialPassableItemGroupChoices.v1(name%2Cdescription%2CitemIds)%2ConDemandCourseMaterialPassableLessonElements.v1(gradingWeight%2CisRequiredForPassing)%2ConDemandCourseMaterialItems.v2(name%2Cslug%2CtimeCommitment%2CcontentSummary%2CisLocked%2ClockableByItem%2CitemLockedReasonCode%2CtrackId%2ClockedStatus%2CitemLockSummary)%2ConDemandCourseMaterialTracks.v1(passablesCount)&showLockedItems=true getting page https://api.coursera.org/api/onDemandCourseMaterials.v2/?q=slug&slug=scholoarly-communication&includes=modules%2Clessons%2CpassableItemGroups%2CpassableItemGroupChoices%2CpassableLessonElements%2Citems%2Ctracks%2CgradePolicy&&fields=moduleIds%2ConDemandCourseMaterialModules.v1(name%2Cslug%2Cdescription%2CtimeCommitment%2ClessonIds%2Coptional%2ClearningObjectives)%2ConDemandCourseMaterialLessons.v1(name%2Cslug%2CtimeCommitment%2CelementIds%2Coptional%2CtrackId)%2ConDemandCourseMaterialPassableItemGroups.v1(requiredPassedCount%2CpassableItemGroupChoiceIds%2CtrackId)%2ConDemandCourseMaterialPassableItemGroupChoices.v1(name%2Cdescription%2CitemIds)%2ConDemandCourseMaterialPassableLessonElements.v1(gradingWeight%2CisRequiredForPassing)%2ConDemandCourseMaterialItems.v2(name%2Cslug%2CtimeCommitment%2CcontentSummary%2CisLocked%2ClockableByItem%2CitemLockedReasonCode%2CtrackId%2ClockedStatus%2CitemLockSummary)%2ConDemandCourseMaterialTracks.v1(passablesCount)&showLockedItems=true
> The server replied: {"errorCode":"Not Authorized","message":null,"details":null}
> HTTPError 403 Client Error: Forbidden for url: https://api.coursera.org/api/onDemandCourseMaterials.v2/?q=slug&slug=scholoarly-communication&includes=modules%2Clessons%2CpassableItemGroups%2CpassableItemGroupChoices%2CpassableLessonElements%2Citems%2Ctracks%2CgradePolicy&&fields=moduleIds%2ConDemandCourseMaterialModules.v1(name%2Cslug%2Cdescription%2CtimeCommitment%2ClessonIds%2Coptional%2ClearningObjectives)%2ConDemandCourseMaterialLessons.v1(name%2Cslug%2CtimeCommitment%2CelementIds%2Coptional%2CtrackId)%2ConDemandCourseMaterialPassableItemGroups.v1(requiredPassedCount%2CpassableItemGroupChoiceIds%2CtrackId)%2ConDemandCourseMaterialPassableItemGroupChoices.v1(name%2Cdescription%2CitemIds)%2ConDemandCourseMaterialPassableLessonElements.v1(gradingWeight%2CisRequiredForPassing)%2ConDemandCourseMaterialItems.v2(name%2Cslug%2CtimeCommitment%2CcontentSummary%2CisLocked%2ClockableByItem%2CitemLockedReasonCode%2CtrackId%2ClockedStatus%2CitemLockSummary)%2ConDemandCourseMaterialTracks.v1(passablesCount)&showLockedItems=true
> Sleeping for 60 seconds before downloading next course. You can change this with --download-delay option.
> ```

SOLVED after increasing the `--download-delay` option from default 60s to 120s.
